Repository TeamDATEROAD/DATEROAD-iOS, pull requests merged in 2024-08, with the labels that each got.

#137 [REFACTOR] 리팩토링 (#127)
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseFirst/AddCourseFirstViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseSecond/AddCourseSecondViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleFirst/AddScheduleFirstViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateScheduleViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Login/Views/LoginViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/BannerImageCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/MyRegisterCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/NavViewedCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/ViewedCourseViewController.swift
Labels: ❤️‍🔥 refactor, 🐰 희슬, 🧚🏻 Fairy 윤

#140 [FIX] 1차 QA 이슈 대응 (#200)
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Banners/B_five.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Banners/B_five.imageset/img_banner5.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Banners/B_five.imageset/img_banner5@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Banners/B_five.imageset/img_banner5@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Banners/B_four.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Banners/B_four.imageset/img_banner4.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Banners/B_four.imageset/img_banner4@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Banners/B_four.imageset/img_banner4@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Banners/B_one.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Banners/B_one.imageset/img_banner1.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Banners/B_one.imageset/img_banner1@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Banners/B_one.imageset/img_banner1@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Banners/B_three.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Banners/B_three.imageset/img_banner3.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Banners/B_three.imageset/img_banner3@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Banners/B_three.imageset/img_banner3@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Banners/B_two.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Banners/B_two.imageset/img_banner2.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Banners/B_two.imageset/img_banner2@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Banners/B_two.imageset/img_banner2@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Banners/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/TabBarController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Banner/Views/BannerDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Base/BaseNavBarViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/CourseDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseBottomTabBarView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/ViewModels/MainViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/ViewModels/MyCourseListViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/ViewedCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/ViewModels/PointViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/Views/PointDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Splash/Views/SplashView.swift
Labels: 🩹 fix, 🐰 희슬

#144 [FEAT] 프로필 수정 구현 (#141)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Profile/emptyProfileImg.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Profile/emptyProfileImg.imageset/emptyProfileImg.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Profile/emptyProfileImg.imageset/emptyProfileImg@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Profile/emptyProfileImg.imageset/emptyProfileImg@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Profile/emptyProfileImg.imageset/ic_pf1.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Profile/emptyProfileImg.imageset/ic_pf1@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Profile/emptyProfileImg.imageset/ic_pf1@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Utils/Enums/EditType.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Utils/Enums/TendencyTag.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/User/DTO/PatchEditProfileRequest.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/User/UserService.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/User/UserTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/ViewModels/AddCourseViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/ViewModels/AddScheduleViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/EditProfile/Views/EditProfileViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/ViewModels/MyPageViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/UserInfoView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Onboarding/Views/OnboardingViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Models/ProfileModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/ViewModels/ProfileViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/Cells/TendencyTagCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/ProfileView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/ProfileViewController.swift
Labels: 🛠️ feature, 🐰 희슬, 🌐 network

#146 [FEAT] 자동 로그인 구현 (#145)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Application/SceneDelegate.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/EditProfile/Views/EditProfileViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Login/Views/LoginViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/ViewModels/MyPageViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Onboarding/ViewModels/OnboardingViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Onboarding/Views/OnboardingViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/ProfileViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Splash/ViewModels/SplashViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Splash/Views/SplashViewController.swift
Labels: 🛠️ feature, 🐰 희슬

#148 [FEAT] JWT 토큰 재발급 (#147)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Global/Protocols/Serviceable.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Auth/AuthService.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Auth/AuthTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Auth/DTO/PatchReissueResponse.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Base/BaseService.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Base/NetworkResult.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/ViewModels/AddCourseViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseFirst/AddCourseFirstViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseSecond/AddCourseSecondViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseThird/AddCourseThirdViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/ViewModels/AddScheduleViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleFirst/AddScheduleFirstViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleSecond/AddScheduleSecondViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/CourseDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateScheduleViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateScheduleViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Login/ViewModels/LoginViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Login/Views/LoginViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/ViewModels/MainViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/ViewModels/MyCourseListViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/MyRegisterCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/NavViewedCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/ViewModels/MyPageViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/ViewModels/PointViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/Views/PointDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/ViewModels/ProfileViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/ProfileViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Splash/ViewModels/SplashViewModel.swift
Labels: 🛠️ feature, 🐰 희슬

#150 [REFACTOR] 코스 둘러보기 리팩토링 (#143)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Base/NetworkService.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Commons/LocationFilter/LocationFilterViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Commons/LocationFilter/Models/LocationModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Commons/LocationFilter/Views/Cells/CityLabelCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Commons/LocationFilter/Views/Cells/CountryLabelCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Commons/LocationFilter/Views/LocationFilterView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Commons/LocationFilter/Views/LocationFilterViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/ViewModels/CourseViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseFilterView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseNavigationBarView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseViewController.swift
Labels: ❤️‍🔥 refactor, 🫧 민서

#154 [CHORE] CustomAlertView 디자인 수정사항 반영 (#153)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/xcshareddata/xcschemes/DATEROAD-iOS.xcscheme
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/CustomAlert/DRCustomAlertView.swift
Labels: 🐣 수민, 🌀 chore

#155 [REFACTOR] 코스 상세 버그 수정 및 리팩토링 (#151)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Global/Extensions/UIImageView+.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Commons/LocationFilter/Views/LocationFilterView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/Cells/CourseListCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/ImageCarouselCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Models/CourseDetailModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/CourseDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/ContentMaskView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailBottomTabBarView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/DeleteCourseSettingView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainViewController.swift
Labels: ❤️‍🔥 refactor, 🫧 민서

#159 [FIX] 메인 뷰 자체 QA 적용 (#152)
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Protocols/MainSectionLayout.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Protocols/Serviceable.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Main/DTO/GetMainUserProfileResponse.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseFirst/AddCourseFirstViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseSecond/AddCourseSecondViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseThird/AddCourseThirdViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleFirst/AddScheduleFirstViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleSecond/AddScheduleSecondViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/ViewModels/CourseViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateScheduleViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Login/Views/LoginViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/MainHeaderView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/UpcomingDateCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/DateTicketView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/MyRegisterCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/NavViewedCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/ViewedCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/Views/PointDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/ProfileViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Splash/ViewModels/SplashViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Splash/Views/SplashViewController.swift
Labels: 🩹 fix, 🐰 희슬

#161 [FEAT] 코스 상세 변경된 GUI 적용 및 플로우 수정 (#160)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/xcshareddata/xcschemes/DATEROAD-iOS.xcscheme
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Utils/Enums/AlertType.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Banner/Views/BannerDetailView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Banner/Views/BannerDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/MainContentsCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/CourseDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/GradientView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/InfoBarView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/InfoHeaderView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/StickyHeaderNavBarView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/TimelineHeaderView.swift
Labels: 🛠️ feature, 🫧 민서

#158 [FIX] '코스 등록', '일정 등록' 변경 사항에 따른 코드 수정 (#156)
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/ViewModels/AddCourseViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseFirst/AddCourseFirstViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/ViewModels/AddScheduleViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleFirst/AddScheduleFirstViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Commons/LocationFilter/Models/LocationModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Commons/LocationFilter/Views/LocationFilterView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Commons/LocationFilter/Views/LocationFilterViewController.swift
Labels: 🩹 fix, 🐼 신영, 😙 개멍청이슈

#166 [REFACTOR] 코스 둘러보기 자체 QA 및 리팩토링 (#157)
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Course/img_course_empty.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Course/img_course_empty.imageset/img_031-1.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Course/img_course_empty.imageset/img_031-1.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Course/img_course_empty.imageset/img_031-1@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Course/img_course_empty.imageset/img_031-1@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Commons/LocationFilter/Views/LocationFilterViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Models/CourseListModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/Cells/CourseListCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseFilterView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseListView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseNavigationBarView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/ViewModels/MainViewModel.swift
Labels: ❤️‍🔥 refactor, 🫧 민서

#168 [REFACTOR] 메인뷰 리팩토링 (#165)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Protocols/MainSectionLayout.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/ViewModels/MainViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/BannerCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/BannerImageCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/BannerIndexFooterView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/MainHeaderView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainViewController.swift
Labels: 🛠️ feature, ❤️‍🔥 refactor, 🐰 희슬, 😙 개멍청이슈, 🧚🏻 Fairy 윤

#171 [REFACTOR] 코스 둘러보기 & 코스 상세 로딩뷰/에러뷰 적용 (#167)
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/ViewModels/CourseViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/CourseDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
Labels: ❤️‍🔥 refactor, 🫧 민서

#172 [FIX] 관리자 상세 페이지 자체 QA (#169)
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Banner/Views/BannerDetailView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Banner/Views/BannerDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Banner/Views/Cells/BannerInfoHeaderView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/CourseDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/BottomPageControllView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/StickyHeaderNavBarView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/ViewModels/MainViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/BannerIndexFooterView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/HotDateCourseCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainViewController.swift
Labels: 🩹 fix, 🐰 희슬, 🧚🏻 Fairy 윤

#180 [FEAT] 스택 & 토큰 처리 (#173)
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseFirst/AddCourseFirstViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateScheduleViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/DateTicketView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/EmptyTicketView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/ViewModels/MyPageViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/Views/PointDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Splash/ViewModels/SplashViewModel.swift
Labels: 🛠️ feature, 🐰 희슬

#177 [REFACTOR] 데이트일정 리팩토링 (#163)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/xcshareddata/xcschemes/DATEROAD-iOS.xcscheme
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/Cells/PastDateCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/DateDetailContentView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateScheduleViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateScheduleViewModel.swift
Labels: ❤️‍🔥 refactor, 🐣 수민, 😙 개멍청이슈

#182 [REFACTOR] 내가 열람한 코스 리팩토링 (#149)
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/ViewModels/MyCourseListViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/MyRegisterCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/NavViewedCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/ViewedCourseViewController.swift
Labels: ❤️‍🔥 refactor, 🐣 수민

#179 [FIX] 데이트 일정 & 지난 데이트 이슈 해결 (#178)
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/TabBarController.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/DateSchedule/DateScheduleService.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateScheduleViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateScheduleViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/DateTicketView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/EmptyTicketView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainViewController.swift
Labels: 🩹 fix, 🐰 희슬

#174 [REFACTOR] 코스, 일정 등록하기 리펙토링 (#142)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Global/Extensions/UINavigationController+.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/DRDateFormatterManager.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/ViewModels/AddCourseViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseThird/AddCourseThirdViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/ViewModels/AddScheduleViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleSecond/AddScheduleSecondViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Commons/LocationFilter/Views/LocationFilterViewController.swift
Labels: ❤️‍🔥 refactor, 🐼 신영

#176 [FIX] 코스 상세보기 자체 QA (#170)
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/CourseDetail/img_preview.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/CourseDetail/img_preview.imageset/ddd.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/CourseDetail/img_preview.imageset/img_034.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/CourseDetail/img_preview.imageset/img_034@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/CourseDetail/img_preview.imageset/img_034@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/ContentMaskView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
Labels: 🩹 fix, 🫧 민서

#185 [FIX] 온보딩 자체 QA (#181)
  DATEROAD-iOS/DATEROAD-iOS/Global/Extensions/String+.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Onboarding/secondOnboardingBG.imageset/img_0122_ios.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Onboarding/secondOnboardingBG.imageset/img_0122_ios@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Onboarding/secondOnboardingBG.imageset/img_0122_ios@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Profile/emptyProfileImg.imageset/ic_pf1.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Profile/emptyProfileImg.imageset/ic_pf1@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Profile/emptyProfileImg.imageset/ic_pf1@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/ViewModels/ProfileViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/ProfileViewController.swift
Labels: 🩹 fix, 🐰 희슬

#186 Fix/#175
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseFirst/AddFirstView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseSecond/AddCourseSecondViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseSecond/AddSecondView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleFirst/InAddScheduleFirstView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleSecond/AddScheduleSecondViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleSecond/InAddScheduleSecondView.swift
Labels: 🩹 fix, 🐼 신영
