Repository TeamDATEROAD/DATEROAD-iOS, pull requests merged in 2024-11, with the labels that each got.

#261 [REFACTOR] 스켈레톤뷰 적용 (#260)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Global/Extensions/UIView+.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/DateSchedule/card.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/DateSchedule/card.imageset/btn_card.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/DateSchedule/card.imageset/btn_card@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/DateSchedule/card.imageset/btn_card@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Loading/placeholderImage.imageset/2FF0B64C-E5D8-40EB-B27F-8C2F7D9285A3_1_102_o 2.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Loading/placeholderImage.imageset/2FF0B64C-E5D8-40EB-B27F-8C2F7D9285A3_1_102_o 2@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Loading/placeholderImage.imageset/2FF0B64C-E5D8-40EB-B27F-8C2F7D9285A3_1_102_o 2@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Loading/placeholderImage.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Skeleton/BannerDetailSkeletonView.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Skeleton/CourseDetailSkeletonView.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Skeleton/CourseItemSkeletonView.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Skeleton/CourseSkeletonView.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Skeleton/DetailContentView.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Skeleton/MainSkeletonView.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Skeleton/MyCourseItemSkeletonView.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Skeleton/MyRegisterCourseSkeletonView.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Skeleton/UpcomingDateScheduleSkeletonView.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Skeleton/ViewedCourseSkeletonView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Banner/Views/BannerDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Base/BaseNavBarViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Base/BaseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/Cells/CourseListCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseListView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/ImageCarouselCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/CourseDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateScheduleViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateScheduleViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/ViewModels/MyCourseListViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/Cells/MyCourseListCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/MyRegisterCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/NavViewedCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/ViewedCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/ViewModels/MyPageViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/Cells/MyPageTableViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/UserInfoView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/Views/PointDetailViewController.swift
Labels: ❤️‍🔥 refactor

#263 [UPDATE] 1.0.3 버전 업데이트 (#262)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Global/Extensions/UIView+.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/DateSchedule/card.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/DateSchedule/card.imageset/btn_card.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/DateSchedule/card.imageset/btn_card@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/DateSchedule/card.imageset/btn_card@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Loading/placeholderImage.imageset/2FF0B64C-E5D8-40EB-B27F-8C2F7D9285A3_1_102_o 2.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Loading/placeholderImage.imageset/2FF0B64C-E5D8-40EB-B27F-8C2F7D9285A3_1_102_o 2@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Loading/placeholderImage.imageset/2FF0B64C-E5D8-40EB-B27F-8C2F7D9285A3_1_102_o 2@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Loading/placeholderImage.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Skeleton/BannerDetailSkeletonView.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Skeleton/CourseDetailSkeletonView.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Skeleton/CourseItemSkeletonView.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Skeleton/CourseSkeletonView.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Skeleton/DetailContentView.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Skeleton/MainSkeletonView.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Skeleton/MyCourseItemSkeletonView.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Skeleton/MyRegisterCourseSkeletonView.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Skeleton/UpcomingDateScheduleSkeletonView.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Skeleton/ViewedCourseSkeletonView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Banner/Views/BannerDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Base/BaseNavBarViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Base/BaseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/Cells/CourseListCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseListView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/ImageCarouselCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/CourseDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateScheduleViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateScheduleViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/ViewModels/MyCourseListViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/Cells/MyCourseListCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/MyRegisterCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/NavViewedCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/ViewedCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/ViewModels/MyPageViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/Cells/MyPageTableViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/UserInfoView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/Views/PointDetailViewController.swift
Labels: 🐰 희슬, 💎 update

#265 [REFACTOR] 데이터 로딩 리팩토링 (#264)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Global/Extensions/UIImageView+.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/clearLoading.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Skeleton/BannerDetailSkeletonView.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Utils/ObservablePattern.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Banner/Models/BannerDetailModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Banner/ViewModels/BannerViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Banner/Views/BannerDetailView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Banner/Views/BannerDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Base/BaseNavBarViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Base/BaseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/ImageCarouselCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Models/CourseDetailModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/CourseDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/Model/DateScheduleModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Login/Models/LoginModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Login/Views/LoginViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Models/MainModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/ViewModels/MainViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/BannerCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/HotDateCourseCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/MainHeaderView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/NewDateCourseCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/UpcomingDateCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Models/MyCourseListModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/Cells/MyCourseListCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/ViewedCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Models/MyPageModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/Models/PointModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Models/ProfileModel.swift
Labels: ❤️‍🔥 refactor, 🐰 희슬

#267 [Fix] QA 적용 및 데이터 로딩 방식 변경 (#266)
  DATEROAD-iOS/DATEROAD-iOS/Global/Extensions/UIImageView+.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/DRBottomSheetViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Cells/AddSecondViewTableViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseFirst/AddCourseFirstViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseSecond/AddCourseSecondViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseSecond/AddSecondView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddSheetViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleBottomSheetViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleFirst/AddScheduleFirstViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleSecond/AddScheduleSecondViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleSecond/InAddScheduleSecondView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Banner/Models/BannerDetailModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Banner/ViewModels/BannerViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Banner/Views/BannerDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Commons/LocationFilter/Views/LocationFilterView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Commons/LocationFilter/Views/LocationFilterViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Models/CourseListModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/ViewModels/CourseViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Models/CourseDetailModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/CourseDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateScheduleViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateScheduleViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Models/MyCourseListModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/ViewModels/MyCourseListViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/Cells/MyCourseListCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/MyRegisterCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/NavViewedCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/ViewedCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/ViewModels/MyPageViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/UserInfoView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/ViewModels/PointViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/Views/PointDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/EditProfileViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/ProfileViewController.swift
Labels: 🩹 fix, 🐼 신영, 😙 개멍청이슈, ⚽️ 매서운 트러블 슈팅 뻥

#270 [HOTFIX] 이슈 해결 (#268)
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseThird/AddCourseThirdViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/ViewModels/AddScheduleViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleSecond/AddScheduleSecondViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Base/BaseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/ViewModels/CourseViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseListView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/Cells/DateCardCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateScheduleView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateScheduleViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/MainHeaderView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/UpcomingDateCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/Cells/MyCourseListCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/MyRegisterCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/ViewedCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/UserInfoView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/Views/PointDetailView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/EditProfileViewController.swift
Labels: 🐰 희슬, 🧚🏻 Fairy 윤, 🔥 hotfix

#271 [HOTFIX] Troubleshooting various issues (#269)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Global/Extensions/UITextView+.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/CustomEmptyView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Cells/AddSecondViewTableViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseFirst/AddFirstView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseSecond/AddSecondView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseThird/AddCourseThirdViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseThird/AddThirdView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/ViewModels/AddScheduleViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleFirst/AddScheduleFirstViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleFirst/InAddScheduleFirstView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleSecond/AddScheduleSecondViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleSecond/InAddScheduleSecondView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Base/BaseNavBarViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Commons/LocationFilter/Views/LocationFilterViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/Cells/CourseListCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/MainContentsCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/TimelineInfoCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/TitleInfoCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/Cells/DateCardCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/Cells/DateTimeLineCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/Cells/PastDateCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/DateDetailContentView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateScheduleViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/HotDateCourseCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/NewDateCourseCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/DateTicketView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/Cells/MyCourseListCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/MyRegisterCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/ViewedCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/ProfileView.swift
Labels: 🐼 신영, 🔥 hotfix

#273 [HOTFIX] 프로필(등록, 변경), 열람한코스(탭바) 수정 (#272)
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/ViewModels/MyCourseListViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/EditProfileViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/ProfileViewController.swift
Labels: 🐼 신영, 🔥 hotfix

#275 [UPDATE] 1.0.4 업데이트 (#274)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Global/Skeleton/UpcomingDateScheduleSkeletonView.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/CustomAlert/DRCustomAlertView.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/CustomEmptyView.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/DRErrorViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Cells/AddCourseImageCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Cells/AddSecondViewTableViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseFirst/AddCourseFirstView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseFirst/AddFirstView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseSecond/AddCourseSecondView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseSecond/AddSecondView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseThird/AddThirdView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleFirst/InAddScheduleFirstView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleSecond/InAddScheduleSecondView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Banner/Views/Cells/BannerInfoHeaderView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Commons/LocationFilter/Views/LocationFilterView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/Cells/CourseListCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseNavigationBarView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/DeleteCourseSettingView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/TimelineHeaderView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/Cells/DateCardCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/Cells/DateTimeLineCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/Cells/PastDateCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/DateDetailContentView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/DateScheduleDeleteView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/HotDateCourseCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/MainHeaderView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/NewDateCourseCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/DateTicketView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/EmptyTicketView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Onboarding/Views/Cells/OnboardingCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointSystem/Views/Cells/PointSystemCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/ProfileImageSettingView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/ProfileView.swift
Labels: 🐰 희슬, 💎 update

#278 [HOTFIX] '일정 등록' 뷰 1 Tag titleLabel 관련 버그 수정 (#277)
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/ViewModels/AddScheduleViewModel.swift
Labels: 🐼 신영, 😙 개멍청이슈, 🔥 hotfix

#280 [HOTFIX] '프로필 변경' 관련 버그 수정 (#279)
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/ViewModels/ProfileViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/EditProfileViewController.swift
Labels: 🐼 신영, 🔥 hotfix

#281 [UPDATE] 1.0.5 버전 업데이트
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/ViewModels/AddScheduleViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/ViewModels/ProfileViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/EditProfileViewController.swift
Labels: 🐰 희슬, 💎 update
