Repository TeamDATEROAD/DATEROAD-iOS, pull requests merged in 2024-09, with the labels that each got.

#187 [REFACTOR] 포인트내역 리팩토링 (#183)
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/ViewModels/PointViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/Views/PointDetailViewController.swift
Labels: ❤️‍🔥 refactor, 🐣 수민

#190 [CHORE] 엠티뷰 디자인 변경사항 적용 (#188)
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Course/img_course_empty.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Course/img_course_empty.imageset/img_031-1.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Course/img_course_empty.imageset/img_031-1@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Course/img_course_empty.imageset/img_031-1@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Course/img_course_empty.imageset/img_031_1.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyDateSchedule.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyDateSchedule.imageset/img_041-1 1.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyDateSchedule.imageset/img_041-1 2.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyDateSchedule.imageset/img_041-1.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyDateSchedule.imageset/img_041_1.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyGainedPoint.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyGainedPoint.imageset/img_0224.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyGainedPoint.imageset/img_0224@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyGainedPoint.imageset/img_0224@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyGainedPoint.imageset/img_022_3.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyMyRegisterCourse.imageset/img_054.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyMyRegisterCourse.imageset/img_054@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyMyRegisterCourse.imageset/img_054@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyPastSchedule.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyPastSchedule.imageset/img_0451-2 1.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyPastSchedule.imageset/img_0451-2 2.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyPastSchedule.imageset/img_0451-2.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyPastSchedule.imageset/img_045_1.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyUsedPoint.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyUsedPoint.imageset/img_0225.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyUsedPoint.imageset/img_0225@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyUsedPoint.imageset/img_0225@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyUsedPoint.imageset/img_022_4.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyViewedCourse.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyViewedCourse.imageset/img_0231-3.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/CustomEmptyView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseListView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/MyRegisterCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/ViewedCourseViewController.swift
Labels: 🐣 수민, 🌀 chore

#193 [FIX] 코스 상세 QA 반영 (#191)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/xcshareddata/xcschemes/DATEROAD-iOS.xcscheme
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/CourseDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/GradientView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/StickyHeaderNavBarView.swift
Labels: 🩹 fix, 🫧 민서

#196 [FIX] 1차 iOS QA 적용 (#195)
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Protocols/MainSectionLayout.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/ViewModels/MainViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/HotDateCourseCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/MainHeaderView.swift
Labels: 🩹 fix, 🐰 희슬

#204 [FIX] Auth 관련 QA 적용 (#201)
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Protocols/Serviceable.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/ViewModels/AddCourseViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/ViewModels/AddScheduleViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/ViewModels/CourseViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/CourseDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateScheduleViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Login/ViewModels/LoginViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/ViewModels/MainViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/ViewModels/MyCourseListViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/ViewModels/MyPageViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/ViewModels/PointViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/ViewModels/ProfileViewModel.swift
Labels: 🩹 fix, 🐰 희슬, 🧚🏻 Fairy 윤

#207 [FIX] 로딩뷰 & 에러뷰 변경사항 적용 (#205)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Error/errorImage.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Error/errorImage.imageset/img_0121_aos.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Error/errorImage.imageset/img_0121_aos@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Error/errorImage.imageset/img_0121_aos@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Error/errorImage.imageset/img_061.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Error/errorImage.imageset/img_061@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Error/errorImage.imageset/img_061@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/loading.json
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/DRErrorViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/TabBarController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseThird/AddCourseThirdViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleFirst/AddScheduleFirstViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleSecond/AddScheduleSecondViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Banner/Views/BannerDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Base/BaseNavBarViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Base/BaseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/ViewModels/CourseViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateScheduleViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateScheduleViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Login/Views/LoginViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/ViewModels/MyCourseListViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/MyCourseListView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/MyRegisterCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/NavViewedCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/ViewedCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/ViewModels/MyPageViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/Views/PointDetailViewController.swift
Labels: 🩹 fix, 🐰 희슬, 🧚🏻 Fairy 윤

#210 [FEAT] 엠플리튜드 초기 세팅 & 메인 적용 (#206)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/xcshareddata/xcschemes/DATEROAD-iOS.xcscheme
  DATEROAD-iOS/DATEROAD-iOS/Application/AppDelegate.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Service/AmplitudeManager.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Settings/Configurations/Config.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Settings/Configurations/Development.xcconfig
  DATEROAD-iOS/DATEROAD-iOS/Global/Settings/Info.plist
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/TabBarController.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Utils/Enums/Header.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/AddCourse/AddCourseTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/AddSchedule/AddScheduleTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Auth/AuthTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Course/CourseTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/CourseDetail/CourseDetailTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/CourseDetail/LikeCourseService.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/CourseDetail/LikeCourseTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/CourseDetail/UsePointTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/DateSchedule/DateScheduleTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Main/MainTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/MyCourse/MyCourseTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/PointDetail/PointDetailTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/User/UserTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Base/BaseNavBarViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Base/BaseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Login/ViewModels/LoginViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Login/Views/LoginViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Models/MainModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/ViewModels/MainViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/ViewModels/MyCourseListViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/MyCourseListView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/MyRegisterCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/NavViewedCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/ViewedCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Models/MyPageModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/ViewModels/MyPageViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Onboarding/Views/OnboardingViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/ViewModels/ProfileViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/ProfileViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Splash/ViewModels/SplashViewModel.swift
Labels: 🛠️ feature, 🐰 희슬

#211 [REFACTOR] 코스 상세 Compositonal Layout 리팩토링 (#198)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Global/Service/DRCompositionalLayoutFactory.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Utils/CollectionViewUtils.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
Labels: ❤️‍🔥 refactor, 🫧 민서

#212 [FIX] 코스, 일정 등록 중 '장소 등록' 레이아웃 오류 (#209)
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseSecond/AddSecondView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleSecond/AddScheduleSecondView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleSecond/AddScheduleSecondViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleSecond/InAddScheduleSecondView.swift
Labels: 🩹 fix, 🐼 신영

#217 [FIX] 1차 QA 반영 마무리 (#213)
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/Cells/DateCardCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/Cells/PastDateCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/DateDetailContentView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateScheduleViewController.swift
Labels: 🩹 fix, 🐣 수민

#219 [FEAT] Amplitude 나머지 적용 (#214)
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/TabBarController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateScheduleViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateScheduleViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/ViewModels/MainViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/ViewModels/MyCourseListViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/ViewedCourseViewController.swift
Labels: 🛠️ feature, 🐰 희슬

#223 [FIX] 2차 QA 전 디테일 수정 (#220)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Application/AppDelegate.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Banner/Views/BannerDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/ViewModels/CourseViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/CourseDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateScheduleViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateScheduleViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/ViewModels/MainViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/ViewModels/MyCourseListViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/ViewedCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/ViewModels/MyPageViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageViewController.swift
Labels: 🩹 fix, 🐰 희슬

#222 [FIX] 2차 QA 이전 버그 수정 (#221)
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseThird/AddCourseThirdViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseThird/AddThirdView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleFirst/AddScheduleFirstViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleSecond/AddScheduleSecondViewController.swift
Labels: 🩹 fix, 🐼 신영

#226 [FIX] 데이트일정 삭제 후 pageControl 보이는 오류 해결 (#225)
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateScheduleViewController.swift
Labels: 🩹 fix, 🐣 수민

#233 [FIX] iOS 2차 QA 적용 (#231)
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseSecond/AddCourseSecondViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseThird/AddCourseThirdViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseThird/AddThirdView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleSecond/AddScheduleSecondViewController.swift
Labels: 🩹 fix, 🐼 신영

#235 [FEAT] 데이트일정 및 열람한 코스 Amplitude 적용 (#218)
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/CustomAlert/DRCustomAlertViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Base/BaseNavBarViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/Model/DateScheduleModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateScheduleViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateScheduleViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/ViewModels/MyCourseListViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/NavViewedCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/ViewedCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/ViewModels/PointViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/Views/PointDetailViewController.swift
Labels: 🛠️ feature, 🐣 수민

#237 [FEAT] '일정 등록' & '코스 등록' 관련 Amplitude 적용 (#215)
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Cells/AddCourseImageCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Cells/AddSecondViewTableViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/ViewModels/AddCourseViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseFirst/AddCourseFirstView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseFirst/AddCourseFirstViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseFirst/AddFirstView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseSecond/AddCourseSecondView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseSecond/AddCourseSecondViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseSecond/AddSecondView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseThird/AddCourseThirdView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseThird/AddCourseThirdViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseThird/AddThirdView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddSheetView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddSheetViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/ViewModels/AddScheduleViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleBottomSheetView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleBottomSheetViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleFirst/AddScheduleFirstView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleFirst/AddScheduleFirstViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleFirst/InAddScheduleFirstView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleSecond/AddScheduleSecondView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleSecond/AddScheduleSecondViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleSecond/InAddScheduleSecondView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateScheduleViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/NavViewedCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/ViewModels/MyPageViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/UserInfoView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/ViewModels/ProfileViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/EditProfileViewController.swift
Labels: 🛠️ feature, 🐼 신영

#238 [FIX] 2차 QA 반영 #232
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Global/Extensions/Int+.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/CostInfoCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
Labels: 🩹 fix, 🫧 민서

#239 [FEAT] 코스 상세 Amplitude 적용 (#216)
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/CourseDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
Labels: 🛠️ feature, 🫧 민서

#241 [Feat] 버전 & 빌드 번호 업데이트 (#236)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Global/Settings/Configurations/Development.xcconfig
Labels: 🐰 희슬

#244 [HOTFIX] 1.0.0 버전 수정사항 적용 (#243)
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Base/NetworkResult.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/Cells/CourseListCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/CourseDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateScheduleViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/ViewModels/MainViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/UpcomingDateCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/ViewModels/PointViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/ViewModels/ProfileViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/EditProfileViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/ProfileViewController.swift
Labels: 🐰 희슬, 🔥 hotfix

#246 [HOTFIX] 1.0.0 버전 수정사항 적용 (#243)
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Base/NetworkResult.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/Cells/CourseListCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/CourseDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateScheduleViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/ViewModels/MainViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/UpcomingDateCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/ViewModels/PointViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/ViewModels/ProfileViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/EditProfileViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/ProfileViewController.swift
Labels: 🐰 희슬, 🔥 hotfix
