Repository TeamDATEROAD/DATEROAD-iOS, pull requests merged in 2024-07, with the labels that each got.

#11 [CHORE] 컬러 세팅
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/GrayScale/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/GrayScale/DR_Black.colorset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/GrayScale/DR_White.colorset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/GrayScale/Gray100.colorset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/GrayScale/Gray200.colorset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/GrayScale/Gray300.colorset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/GrayScale/Gray400.colorset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/GrayScale/Gray500.colorset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/GrayScale/Gray600.colorset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/Main/AlertRed.colorset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/Main/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/Main/DeepPurple.colorset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/Main/LightLime.colorset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/Main/LightPurple.colorset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/Main/Lilac.colorset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/Main/Lime.colorset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/Main/MediumPurple.colorset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/Main/Pink.colorset/Contents.json
Labels: 🐣 수민, 🌀 chore

#9 [FEAT] 커스텀네비게이션바 구현 (#6)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/NavBarIcon/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/NavBarIcon/leftArrow.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/NavBarIcon/leftArrow.imageset/ic-left.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Fonts/SUIT-Bold.otf
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Fonts/SUIT-ExtraBold.otf
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Fonts/SUIT-Medium.otf
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Fonts/SUIT-Regular.otf
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Fonts/SUIT-SemiBold.otf
  DATEROAD-iOS/DATEROAD-iOS/Global/Settings/Info.plist
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Base/BaseNavBarViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Base/BaseViewController.swift
Labels: 🛠️ feature, 🐣 수민

#8 [FEAT] 로그인 UI 구현 (#7)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Application/AppDelegate.swift
  DATEROAD-iOS/DATEROAD-iOS/Application/SceneDelegate.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Extensions/UIButton+.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Settings/Configurations/Config.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Settings/Configurations/Development.xcconfig
  DATEROAD-iOS/DATEROAD-iOS/Global/Settings/Info.plist
  DATEROAD-iOS/DATEROAD-iOS/Global/Utils/Enums/SocialType.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Utils/Enums/UserType.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Utils/ObservablePattern.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Utils/ScreenUtils.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Base/BaseView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Login/Models/LoginModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Login/ViewModels/LoginViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Login/Views/LoginView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Login/Views/LoginViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Splash/Views/SplashView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Splash/Views/SplashViewController.swift
Labels: 🛠️ feature, 🐰 희슬

#16 [SETTING] 폰트 세팅 (#14)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Global/Extensions/UIFont+.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Base/BaseNavBarViewController.swift
Labels: ⚙️ setting, 🐰 희슬

#18 [FEAT] 코스 상세보기 레이아웃 구현 (#5)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Application/SceneDelegate.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/CoastInfoCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/ImageCarouselCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/LikeCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/MainContentsCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/TagInfoCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/TimelineInfoCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Models/CourseDetailModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/CoastInfoViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/CourseDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/ImageCarouselViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/LikeViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/MainContentsViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/TagInfoViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/TimelineInfoViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/BottomPageControllView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/InfoHeaderView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Login/Views/ViewController.swift
Labels: 🛠️ feature, 🫧 민서

#20 [FEAT] 포인트제도설명 UI 구현(#17)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Application/SceneDelegate.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Extensions/UIButton+.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Extensions/UIFont+.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Extensions/UILabel+.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Protocols/DRButton.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Onboarding/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Onboarding/secondOnboardingBG.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Onboarding/secondOnboardingBG.imageset/secondOnboardingBg.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Onboarding/secondOnboardingBG.imageset/secondOnboardingBg@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Onboarding/secondOnboardingBG.imageset/secondOnboardingBg@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Onboarding/thirdOnboardingBG.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Onboarding/thirdOnboardingBG.imageset/thirdOnboardingBg.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Onboarding/thirdOnboardingBG.imageset/thirdOnboardingBg@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Onboarding/thirdOnboardingBG.imageset/thirdOnboardingBg@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Base/BaseCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Onboarding/Models/OnboardingModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Onboarding/ViewModels/OnboardingViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Onboarding/Views/Cells/OnboardingCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Onboarding/Views/OnboardingView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Onboarding/Views/OnboardingViewController.swift
Labels: 🛠️ feature, 🐰 희슬

#21 [FEAT] 포인트 내역 UI 구현 (#15)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Application/SceneDelegate.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetails/Models/PointModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetails/ViewModels/PointViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetails/Views/Cells/PointCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetails/Views/PointCollectionView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetails/Views/PointDetailsViewController.swift
Labels: 🛠️ feature, 🐣 수민

#26 [FEAT] 프로필 등록 UI 구현 (#22)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DATEROAD-iOS/DATEROAD-iOS/Application/SceneDelegate.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Extensions/String+.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Extensions/UIButton+.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Extensions/UIFont+.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Extensions/UILabel+.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Protocols/DRButtonType.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Protocols/DRErrorType.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Onboarding/secondOnboardingBG.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Onboarding/secondOnboardingBG.imageset/secondOnboardingBg.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Onboarding/secondOnboardingBG.imageset/secondOnboardingBg@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Onboarding/secondOnboardingBG.imageset/secondOnboardingBg@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Onboarding/thirdOnboardingBG.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Onboarding/thirdOnboardingBG.imageset/thirdOnboardingBg.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Onboarding/thirdOnboardingBG.imageset/thirdOnboardingBg@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Onboarding/thirdOnboardingBG.imageset/thirdOnboardingBg@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Profile/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Profile/emptyProfileImg.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Profile/emptyProfileImg.imageset/emptyProfileImg.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Profile/emptyProfileImg.imageset/emptyProfileImg@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Profile/emptyProfileImg.imageset/emptyProfileImg@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Profile/ic_profileplus.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Profile/ic_profileplus.imageset/ic_profileplus.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/DRErrorLabel.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/DRTagButton.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Utils/Enums/TendencyTag.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Base/BaseCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Onboarding/Models/OnboardingModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Onboarding/ViewModels/OnboardingViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Onboarding/Views/Cells/OnboardingCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Onboarding/Views/OnboardingView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Onboarding/Views/OnboardingViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/ViewModels/ProfileViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/Cells/TendencyTagCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/ProfileView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/ProfileViewController.swift
Labels: 🛠️ feature, 🐰 희슬

#27 [FEAT] 코스 상세 열람 전 뷰 (#25)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Global/Extensions/Int+.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Extensions/UIFont+.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/BringCourseCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/CoastInfoCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/ImageCarouselCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/MainContentsCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/TagInfoCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/TimelineInfoCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Models/CourseDetailContents.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Models/ImageContents.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Models/InfoContents.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Models/MainContents.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Models/TimelineContents.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/BringCourseViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/CoastInfoViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/CourseDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/ImageCarouselViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/MainContentsViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/TagInfoViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/TimelineInfoViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/BottomPageControllView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/GradientView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/ImageGradientView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/InfoHeaderView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/PreviewView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/Models/PointModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/ViewModels/PointViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/Views/Cells/PointCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/Views/PointCollectionView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/Views/PointDetailViewController.swift
Labels: 🛠️ feature, 🫧 민서

#28 [FEAT] 내가 열람한 코스 UI 구현 (#23)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DATEROAD-iOS/DATEROAD-iOS/Application/SceneDelegate.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/ViewedCourse/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/ViewedCourse/createCourseArrow.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/ViewedCourse/createCourseArrow.imageset/Vector 1782.svg
  DATEROAD-iOS/DATEROAD-iOS/Presentation/ViewedCourse/Models/ViewedCourseModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/ViewedCourse/ViewModels/ViewedCourseViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/ViewedCourse/Views/Cells/ViewedCourseCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/ViewedCourse/Views/CourseCollectionView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/ViewedCourse/Views/NavViewedCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/ViewedCourse/Views/ViewedCourseViewController.swift
Labels: 🛠️ feature, 🐣 수민

#33 [FEAT] BottomNavigation Bar 구현하기 (#29)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DATEROAD-iOS/DATEROAD-iOS/Application/SceneDelegate.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Icons/ic_home.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Icons/ic_home.imageset/home.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Icons/ic_look.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Icons/ic_look.imageset/course.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Icons/ic_mypage.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Icons/ic_mypage.imageset/my.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Icons/ic_read.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Icons/ic_read.imageset/read.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Icons/ic_timeline.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Icons/ic_timeline.imageset/timeline.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/TabBarController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Base/BaseCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/BringCourseCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/CoastInfoCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/ImageCarouselCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/MainContentsCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/TagInfoCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/TimelineInfoCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
Labels: 🛠️ feature, 🫧 민서

#32 [FEAT] 코스 등록하기 1 UI 및 기능 구현 (#13)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Global/Extensions/UIFont+.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/AddCourse/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/AddCourse/calendar.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/AddCourse/calendar.imageset/ic_calendar.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/AddCourse/camera.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/AddCourse/camera.imageset/ic_camera.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/AddCourse/downArrow.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/AddCourse/downArrow.imageset/downArrow.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/AddCourse/time.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/AddCourse/time.imageset/ic_time.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/TagButtonImages/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/TagButtonImages/tag_alcohol.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/TagButtonImages/tag_alcohol.imageset/tag_Alcohol.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/TagButtonImages/tag_car.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/TagButtonImages/tag_car.imageset/tag_car.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/TagButtonImages/tag_door.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/TagButtonImages/tag_door.imageset/tag_door.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/TagButtonImages/tag_masks.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/TagButtonImages/tag_masks.imageset/tag_Masks.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/TagButtonImages/tag_mountain.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/TagButtonImages/tag_mountain.imageset/tag_Mountain.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/TagButtonImages/tag_paint.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/TagButtonImages/tag_paint.imageset/tag_Paint.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/TagButtonImages/tag_ramen.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/TagButtonImages/tag_ramen.imageset/tag_Ramen.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/TagButtonImages/tag_ring.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/TagButtonImages/tag_ring.imageset/tag_Ring.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/TagButtonImages/tag_shopping.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/TagButtonImages/tag_shopping.imageset/tag_shopping.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/TagButtonImages/tag_skate.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/TagButtonImages/tag_skate.imageset/tag_Skate.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/TagButtonImages/tag_tea.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/TagButtonImages/tag_tea.imageset/tag_tea.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/testImage.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/testImage.imageset/testImage.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/testImage.imageset/testImage@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/testImage.imageset/testImage@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Cells/AddCourseImageCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/ViewModels/AddCourseViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseFirstView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddFirstView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddSheetView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddSheetViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Base/BaseNavBarViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Login/Views/LoginViewController.swift
Labels: 🛠️ feature, 🐼 신영

#36 [FEAT] 마이페이지 UI 구현 (#31)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Protocols/DRButtonType.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/MyPage/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/MyPage/arrow_right_large.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/MyPage/arrow_right_large.imageset/arrow_right_large.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/MyPage/arrow_right_mini.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/MyPage/arrow_right_mini.imageset/arrow_right_mini.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/MyPage/ic_pencil.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/MyPage/ic_pencil.imageset/ic_pencil.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Utils/Constants.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Utils/Enums/MyPageSection.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Base/BaseNavBarViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Base/BaseTableViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Models/MyPageModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/ViewModels/MyPageViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/Cells/MyPageTableViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/Cells/TagCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageMenuView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/UserInfoView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/Views/PointDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/ProfileViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/ViewedCourse/Views/NavViewedCourseViewController.swift
Labels: 🛠️ feature, 🐰 희슬

#40 [FIX] 코스 상세 SE 분기 처리를 통한 레이아웃 설정 (#34)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Application/SceneDelegate.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Extensions/UIButton+.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Protocols/DRButtonType.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Icons/btn_close.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Icons/btn_close.imageset/btn_close.svg
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Commons/LocationFilter/CityLabelCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Commons/LocationFilter/CountryLabelCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Commons/LocationFilter/LocationFilterViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Commons/LocationFilter/LocationModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/BringCourseCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/CoastInfoCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/MainContentsCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/TagInfoCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/TimelineInfoCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/TitleInfoCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Models/MainContents.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/CourseDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
Labels: 🩹 fix, 🫧 민서

#38 [FEAT] 포인트 제도 소개 UI 구현 (#37)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Global/Extensions/UICollectionViewFlowLayout+.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/TabBarController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointSystem/Models/PointSystemModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointSystem/ViewModels/PointSystemViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointSystem/Views/Cells/PointSystemCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointSystem/Views/PointSystemView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointSystem/Views/PointSystemViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/ProfileView.swift
Labels: 🛠️ feature, 🐰 희슬

#45 [FEAT] 스플래시 GUI 적용 (#44)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Application/SceneDelegate.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Protocols/DRButtonType.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/Login/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/Login/kakao_bg.colorset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Login/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Login/kakao_logo.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Login/kakao_logo.imageset/kakao_logo.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Login/logo.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Login/logo.imageset/ic_splashlogo.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Onboarding/secondOnboardingBG.imageset/img_0122_ios.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Onboarding/secondOnboardingBG.imageset/img_0122_ios@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Onboarding/secondOnboardingBG.imageset/img_0122_ios@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Login/Views/LoginView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Login/Views/LoginViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Splash/Views/SplashView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Splash/Views/SplashViewController.swift
Labels: 🛠️ feature, 🐰 희슬

#49 [FEAT] 커스텀 alert 뷰 구현 (#47)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Protocols/DRButtonType.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/CustomAlert/CustomAlertView.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/CustomAlert/CustomAlertViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Utils/Enums/AlertType.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateScheduleViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateScheduleViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageViewController.swift
Labels: 🛠️ feature, 🐣 수민

#59 [FEAT] 메인뷰 UI 구현 (#46)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Protocols/DRButtonType.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Protocols/MainSectionLayout.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Main/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Main/ic_plus.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Main/ic_plus.imageset/ic_plus.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Main/ic_plus_purple.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Main/ic_plus_purple.imageset/ic_plus.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Main/ic_rightarrow_purple.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Main/ic_rightarrow_purple.imageset/ic_rightarrow_purple.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Main/symbol_logo.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Main/symbol_logo.imageset/symbol_logo.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Main/ticket.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Main/ticket.imageset/date_schedule.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Main/ticket.imageset/date_schedule@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Main/ticket.imageset/date_schedule@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/testImage2.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/testImage2.imageset/testImage2.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/testImage2.imageset/testImage2@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/testImage2.imageset/testImage2@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/DRPaddingLabel.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Utils/Enums/MainSection.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Login/ViewModels/LoginViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Models/MainModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/ViewModels/MainViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/BannerCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/BannerImageCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/HotDateCourseCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/MainHeaderView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/NewDateCourseCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/UpcomingDateCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/DateTicketView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/EmptyTicketView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/Cells/TagCollectionViewCell.swift
Labels: 🛠️ feature, 🐰 희슬

#66 [FEAT] 프로필 등록 로직 추가 (#60)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Application/SceneDelegate.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Utils/Enums/ProfileErrorType.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/ViewModels/ProfileViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/ProfileView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/ProfileViewController.swift
Labels: 🛠️ feature, 🐰 희슬

#63 [FEAT] 코스 등록하기 3 UI 및 기능 구현 (#56)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Protocols/DRButtonType.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Icons/ic_addcourseGray.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Icons/ic_addcourseGray.imageset/ic_addcourseGray.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Icons/ic_addcourseWhite.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Icons/ic_addcourseWhite.imageset/ic_addcourse.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Icons/ic_deletecourse.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Icons/ic_deletecourse.imageset/ic_deletecourse.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Icons/ic_movecourse.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Icons/ic_movecourse.imageset/ic_movecourse.svg
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Cells/AddCourseImageCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Cells/AddSecondViewTableViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/ViewModels/AddCoursePlaceModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/ViewModels/AddCourseViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseFirst/AddCourseFirstView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseFirst/AddCourseFirstViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseFirst/AddFirstView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseSecond/AddCourseSecondView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseSecond/AddCourseSecondViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseSecond/AddSecondView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseThird/AddCourseThirdView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseThird/AddCourseThirdViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseThird/AddThirdView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddSheetView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddSheetViewController.swift
Labels: 🛠️ feature, 🐼 신영

#54 [FEAT] 코스 등록하기 2 UI 및 기능 구현 (#35)
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseFirst/AddCourseFirstViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseSecond/AddCourseSecondViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddSheetViewController.swift
Labels: 🛠️ feature, 🐼 신영, 😙 개멍청이슈

#70 [SETTING] 네트워크 세팅 (#67)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Global/Settings/Configurations/Development.xcconfig
  DATEROAD-iOS/DATEROAD-iOS/Global/Settings/Info.plist
  DATEROAD-iOS/DATEROAD-iOS/Network/Base/.gitkeep
  DATEROAD-iOS/DATEROAD-iOS/Network/Base/BaseService.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Base/BaseTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Base/MoyaLoggingPluggin.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Base/NetworkResult.swift
Labels: ⚙️ setting, 🐰 희슬

#65 [FEAT] 데이트일정 카카오톡 공유하기 기능 구현
  DATEROAD-iOS/DATEROAD-iOS/Application/SceneDelegate.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Settings/Configurations/Config.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Settings/Configurations/Development.xcconfig
  DATEROAD-iOS/DATEROAD-iOS/Global/Settings/Info.plist
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/Model/DateScheduleModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/Cells/DateCardCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/Cells/DateTimeLineCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/Cells/PastDateCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/DateDetailContentView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateScheduleViewModel.swift
Labels: 🛠️ feature, 🐣 수민

#73 [FEAT] 2차 변경사항 적용 (#71)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Application/SceneDelegate.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Protocols/DRBottomSheetAction.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/DummyImages/date_schedule.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/DummyImages/date_schedule.imageset/date_schedule.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/DummyImages/date_schedule.imageset/date_schedule@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/DummyImages/date_schedule.imageset/date_schedule@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/DummyImages/img_banner1.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/DummyImages/img_banner1.imageset/img_banner1.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/DummyImages/img_banner1.imageset/img_banner1@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/DummyImages/img_banner1.imageset/img_banner1@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/DummyImages/img_banner2.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/DummyImages/img_banner2.imageset/img_banner2.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/DummyImages/img_banner2.imageset/img_banner2@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/DummyImages/img_banner2.imageset/img_banner2@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/DummyImages/img_banner3.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/DummyImages/img_banner3.imageset/img_banner3.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/DummyImages/img_banner3.imageset/img_banner3@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/DummyImages/img_banner3.imageset/img_banner3@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/DummyImages/img_banner4.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/DummyImages/img_banner4.imageset/img_banner4.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/DummyImages/img_banner4.imageset/img_banner4@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/DummyImages/img_banner4.imageset/img_banner4@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/DummyImages/img_banner5.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/DummyImages/img_banner5.imageset/img_banner5.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/DummyImages/img_banner5.imageset/img_banner5@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/DummyImages/img_banner5.imageset/img_banner5@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Settings/Info.plist
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/DRBottomSheetViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Utils/Enums/TendencyTag.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Models/MainModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/ViewModels/MainViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/BannerImageCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Models/ProfileModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/ViewModels/ProfileViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/Cells/TendencyTagCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/ProfileImageSettingView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/ProfileView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/ProfileViewController.swift
Labels: 🛠️ feature, 🐰 희슬, 🧚🏻 Fairy 윤

#68 [Feat] 코스 상세 UI & 분기 처리 구현 (#53)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DATEROAD-iOS/DATEROAD-iOS/Global/Extensions/Float+.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Extensions/Int+.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Extensions/String+.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Protocols/DRButtonType.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/CourseDetail/img_preview.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/CourseDetail/img_preview.imageset/ddd.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/NavBarIcon/btn_more.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/NavBarIcon/btn_more.imageset/btn_more.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/CustomAlert/CustomAlertViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/TabBarController.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Utils/Enums/AlertType.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Base/BaseNavBarViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Base/BaseView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Models/CoastModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Models/CourseDetailTitleModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Models/ImageModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Models/InfoBarModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Models/MainContentsModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Models/TimelineModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseFilterView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseListView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/MainContentsCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/TagInfoCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/TimelineInfoCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/TitleInfoCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Models/CourseDetailModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Models/DateInfoModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Models/MainContentsModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Models/TimelineModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/CourseDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/BottomPageControllView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseInfoTabBarView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/ImageGradientView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/InfoBarView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/InfoHeaderView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/PreviewView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/VisitDateView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateScheduleViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PreviewCourseDetail/Models/PreviewCourseDetailModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PreviewCourseDetail/ViewModels/PreviewCourseDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PreviewCourseDetail/Views/ContentMaskView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PreviewCourseDetail/Views/DeleteCourseSettingView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PreviewCourseDetail/Views/PreviewCourseDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PreviewCourseDetail/Views/PreviewView.swift
Labels: 🛠️ feature, 🫧 민서, 😙 개멍청이슈

#72 [FIX] 코스 둘러보기 GUI 수정 사항 반영 & 버튼 에러 해결 (#69)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Application/SceneDelegate.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/TabBarController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Models/CourseListModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/ViewModels/CourseViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/Cells/CourseCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/Cells/CourseListCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseFilterView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseListView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseNavigationBarView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateScheduleView.swift
Labels: 🛠️ feature, 🫧 민서, 😙 개멍청이슈, ⚽️ 매서운 트러블 슈팅 뻥

#76 [FEAT] 엠티뷰 적용 (#64)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Protocols/DRButtonType.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyGainedPoint.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyGainedPoint.imageset/img_0224 1.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyGainedPoint.imageset/img_0224 2.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyGainedPoint.imageset/img_0224.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyMyRegisterCourse.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyMyRegisterCourse.imageset/img_054 1.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyMyRegisterCourse.imageset/img_054 2.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyMyRegisterCourse.imageset/img_054.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyNavViewedCourse.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyNavViewedCourse.imageset/img_0430 1.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyNavViewedCourse.imageset/img_0430 2.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyNavViewedCourse.imageset/img_0430.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyUsedPoint.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyUsedPoint.imageset/img_0225 1.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyUsedPoint.imageset/img_0225 2.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyUsedPoint.imageset/img_0225.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyViewedCourse.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyViewedCourse.imageset/img_0231 1.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyViewedCourse.imageset/img_0231 2.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyViewedCourse.imageset/img_0231.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/CustomAlert/DRCustomAlertView.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/CustomAlert/DRCustomAlertViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/DRBottomSheetViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Utils/Enums/AlertType.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/DateDetailContentView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/DateScheduleDeleteView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateScheduleViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateScheduleViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/ViewModels/PointViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/Views/PointCollectionView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/Views/PointDetailView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/Views/PointDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PreviewCourseDetail/Views/PreviewCourseDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/ViewedCourse/Views/Cells/MyCourseListCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/ViewedCourse/Views/MyCourseListCollectionView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/ViewedCourse/Views/MyRegisterCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/ViewedCourse/Views/NavViewedCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/ViewedCourse/Views/ViewedCourseViewController.swift
Labels: 🛠️ feature, 🐣 수민, 😙 개멍청이슈

#79 [REFACTOR] 코스 등록하기 뷰 공용 컴포넌트 적용 및 리펙토링 (#48)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Icons/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Icons/ic_deletepic.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Icons/ic_deletepic.imageset/Group 1171276354.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Icons/ic_deletepic.imageset/Group 1171276354@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Icons/ic_deletepic.imageset/Group 1171276354@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/CustomImagePicker.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/DRBottomSheetViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Cells/AddCourseImageCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/ViewModels/AddCourseViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseFirst/AddCourseFirstView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseFirst/AddCourseFirstViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseFirst/AddFirstView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseSecond/AddCourseSecondViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseThird/AddCourseThirdView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseThird/AddCourseThirdViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseThird/AddThirdView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddSheetView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddSheetViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/ProfileView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/ProfileViewController.swift
Labels: 🛠️ feature, ❤️‍🔥 refactor, 🐼 신영, ⚽️ 매서운 트러블 슈팅 뻥

#84 [FEAT] 내가 열람한 코스 / 내가 등록한 코스 서버 통신 (#77)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Global/Extensions/Int+.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Base/NetworkService.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/MyCourse/DTO/MyCourseDTO.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/MyCourse/MyCourseService.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/MyCourse/MyCourseTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Models/MyCourseListModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/ViewModels/MyCourseListViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/Cells/MyCourseListCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/MyCourseListCollectionView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/MyRegisterCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/NavViewedCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/ViewedCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/ViewedCourse/Models/MyCourseListModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/ViewedCourse/ViewModels/MyCourseListViewModel.swift
Labels: 🐣 수민, 🌐 network

#87 [FEAT] 포인트내역 서버 통신 (#85)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/CustomAlert/DRCustomAlertViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Base/NetworkService.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/PointDetail/DTO/GetPointDetailResponse.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/PointDetail/PointDetailService.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/PointDetail/PointDetailTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/ViewModels/PointViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/Views/PointDetailViewController.swift
Labels: 🐣 수민, 🌐 network

#88 [FEAT] 데이트일정 서버 통신 (#86)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Global/Extensions/String+.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Base/BaseService.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Base/NetworkService.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/DateSchedule/DTO/DeleteDateScheduleResponse.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/DateSchedule/DTO/GetDateDetailResponse.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/DateSchedule/DTO/GetDateScheduleResponse.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/DateSchedule/DateScheduleService.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/DateSchedule/DateScheduleTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/Model/DateScheduleModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/Cells/DateCardCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/Cells/DateTimeLineCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/Cells/PastDateCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/DateDetailContentView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateContentView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateScheduleView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateScheduleViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateScheduleViewModel.swift
Labels: 🐣 수민, 😙 개멍청이슈, 🌐 network

#89 [FEAT] Auth 관련 서버 통신 구현 (#80)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Application/SceneDelegate.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Utils/Enums/AlertType.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Utils/Enums/SocialType.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Utils/Enums/TendencyTag.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Auth/AuthService.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Auth/AuthTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Auth/DTO/DeleteWithdrawalRequest.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Auth/DTO/PostSignInRequest.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Auth/DTO/PostSignUpRequest.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Auth/DTO/PostSignUpResponse.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Base/BaseService.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Base/EmptyResponse.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Base/NetworkService.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Main/DTO/GetBannerResponse.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Main/DTO/GetMainUserProfileResponse.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Main/MainService.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Main/MainTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/User/DTO/GetUserProfileResponse.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/User/UserService.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/User/UserTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Login/ViewModels/LoginViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Login/Views/LoginViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/ViewModels/MainViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/BannerImageCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/HotDateCourseCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/NewDateCourseCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/UpcomingDateCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Models/MyPageModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/ViewModels/MyPageViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/Cells/TagCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/UserInfoView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Models/ProfileModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/ViewModels/ProfileViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/Cells/TendencyTagCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/ProfileViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Splash/Views/SplashViewController.swift
Labels: 🐰 희슬, 🌐 network

#91 [FIX] 파일 재업로드 (#90)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyGainedPoint.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyGainedPoint.imageset/img_0224.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyGainedPoint.imageset/img_0224@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyGainedPoint.imageset/img_0224@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyMyRegisterCourse.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyMyRegisterCourse.imageset/img_054.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyMyRegisterCourse.imageset/img_054@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyMyRegisterCourse.imageset/img_054@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyUsedPoint.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyUsedPoint.imageset/img_0225.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyUsedPoint.imageset/img_0225@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptyUsedPoint.imageset/img_0225@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/CustomAlert/DRCustomeAlertView.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Main/DTO/GetFilteredDateCourseResponse.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Main/DTO/GetUpcomingDateResponse.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Commons/LocationFilter/LocationFilterViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/DateScheduleDeleteView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Models/MainModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/BannerImageCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/NewDateCourseCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/MyCourseListCollectionView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/MyCourseListView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/MyRegisterCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/NavViewedCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/ViewedCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/ViewModels/PointViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/Views/PointCollectionView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/Views/PointDetailView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/Views/PointDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PreviewCourseDetail/Views/PreviewCourseDetailViewController.swift
Labels: 🩹 fix, 🐰 희슬

#95 [FIX] 회원탈퇴 로직 수정 (#92)
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/ViewModels/ProfileViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/ProfileViewController.swift
Labels: 🩹 fix, 🐰 희슬

#98 [FEAT] 카카오톡 공유하기 연결 (#96)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Global/Settings/Info.plist
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/DRWebViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/DateSchedule/DateScheduleTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateDetailViewModel.swift
Labels: 🛠️ feature, 🐰 희슬

#101 [FEAT] 카카오톡 공유하기 (웹) 구현 (#93)
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/DRWebViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/ViewModels/PointViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/Views/PointDetailViewController.swift
Labels: 🛠️ feature, 🐣 수민, 😙 개멍청이슈

#103 [FIX] 1차 자체 QA 적용 (#99)
  DATEROAD-iOS/DATEROAD-iOS/Network/Main/DTO/GetFilteredDateCourseResponse.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Login/Views/LoginView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Models/MainModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/ViewModels/MainViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/BannerCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/HotDateCourseCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/NewDateCourseCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/UpcomingDateCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/EmptyTicketView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainViewController.swift
Labels: 🩹 fix, 🐰 희슬

#105 [FEAT] '일정 등록 불러오기' & '지난 데이트 코스 등록하기' 구현 (#97)
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/AddCourse/AddCourseService.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/AddCourse/AddCourseTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/AddCourse/DTO/PostAddCourseRequest.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/AddSchedule/AddScheduleService.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/AddSchedule/DTO/PostAddScheduleRequest.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Cells/AddSecondViewTableViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/ViewModels/AddCourseViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseFirst/AddCourseFirstViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseSecond/AddCourseSecondViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseSecond/AddSecondView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseThird/AddCourseThirdViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/ViewModels/AddScheduleViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleFirst/AddScheduleFirstViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleFirst/InAddScheduleFirstView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleSecond/AddScheduleSecondViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleSecond/InAddScheduleSecondView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Base/BaseNavBarViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Commons/LocationFilter/LocationModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/ViewedCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/ViewModels/MyPageViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/Cells/TagCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/Cells/TendencyTagCollectionViewCell.swift
Labels: 🛠️ feature, 🐼 신영, 🌐 network

#109 [FEAT] '일정 등록 불러오기' & '지난 데이트 코스 등록하기' 구현 (#97)
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/ViewModels/AddCourseViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseFirst/AddCourseFirstViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/ViewModels/AddScheduleViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleFirst/AddScheduleFirstViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleSecond/AddScheduleSecondViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/CourseDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/NavViewedCourseViewController.swift
Labels: 🩹 fix, 🛠️ feature, 🐼 신영

#112 [FEAT] 웹뷰 연결 (#104)
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Login/Views/LoginViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageViewController.swift
Labels: 🛠️ feature, 🐰 희슬

#113 [FIX] 좋아요 API 연결 & 필터링 수정 (#107)
  DATEROAD-iOS/DATEROAD-iOS/Global/Extensions/Int+.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Course/CourseService.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Course/CourseTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/CourseDetail/LikeCourseService.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseFirst/AddCourseFirstViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleFirst/AddScheduleFirstViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Commons/LocationFilter/LocationFilterViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/ViewModels/CourseViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/ImageCarouselCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/TagInfoCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/CourseDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseBottomTabBarView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/InfoBarView.swift
Labels: 🩹 fix, 🫧 민서

#117 [FEAT] 메인뷰 화면 연결
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Models/MainModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/ViewModels/MainViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/UpcomingDateCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/DateTicketView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/EmptyTicketView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainViewController.swift
Labels: 🛠️ feature, 🐣 수민

#119 [FIX] 미보완 사항 수정 (#110)
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/ViewModels/MainViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/ViewModels/MyCourseListViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/ViewedCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/ViewModels/MyPageViewModel.swift
Labels: 🩹 fix, 🐼 신영

#125 [FIX] 1차 QA 반영
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateScheduleViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/ViewModels/MyCourseListViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/MyCourseListView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/MyRegisterCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/ViewedCourseViewController.swift
Labels: 🩹 fix, 🐣 수민

#127 [Fix] 마이페이지 총 포인트 실시간 업데이트 안되는 오류 수정 (#126)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/xcshareddata/xcschemes/DATEROAD-iOS.xcscheme
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/ViewModels/MyPageViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageViewController.swift
Labels: 🩹 fix, 🐣 수민

#128 [Fix] 1차 QA (#121)
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/AddCourse/camera_withBg.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/AddCourse/camera_withBg.imageset/btn_addphotosmall.svg
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Cells/AddCourseImageCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseBottomTabBarView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/Cells/DateCardCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/ViewModels/ProfileViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/ProfileViewController.swift
Labels: 🩹 fix, 🐼 신영

#130 [FIX] CourseViewCell 시간값 고정 오류 해결 (#129)
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/Cells/CourseListCollectionViewCell.swift
Labels: 🩹 fix, 🐣 수민

#136 [FIX] 자체 QA (#135)
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Base/BaseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/ViewModels/CourseViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateScheduleViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Login/Views/LoginView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/ViewModels/MainViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/ViewModels/MyCourseListViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/NavViewedCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/ViewModels/MyPageViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Onboarding/ViewModels/OnboardingViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Onboarding/Views/OnboardingViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointSystem/ViewModels/PointSystemViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointSystem/Views/PointSystemViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/ProfileViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Splash/Views/SplashView.swift
Labels: 🩹 fix, 🐼 신영

#138 [FIX] AppIcon 추가 (#135)
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: 🩹 fix, 🐼 신영
