Repository TeamDATEROAD/DATEROAD-iOS, pull requests merged in 2025-04, with the labels that each got.

#300 [FEAT] '코스 등록 화면' 썸네일 기능 구현 등 (#291)
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/DRTimelineView.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Utils/Enums/ImageButtonType.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/AddCourse/AddCourseTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/AddCourse/DTO/PostAddCourseRequest.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/AddCourse/DTO/PostAddCourseResponse.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/AddSchedule/AddScheduleTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/AddSchedule/DTO/PostAddScheduleRequest.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/AddSchedule/DTO/PostAddScheduleResponse.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Cells/AddCourseImageCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/ViewModels/AddCoursePlaceModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/ViewModels/AddCourseViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseFirst/AddCourseFirstViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseSecond/AddCourseSecondViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseThird/AddCourseThirdViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/ViewModels/AddScheduleViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleSecond/AddScheduleSecondViewController.swift
Labels: 🩹 fix, 🛠️ feature, 🐼 신영

#301 [FEAT] 장소 검색 기능 구현 (#299)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Global/Extensions/Encodable+.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptySearchPlace.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptySearchPlace.imageset/img_033_3.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptySearchPlace.imageset/img_033_3@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/EmptyViewImages/emptySearchPlace.imageset/img_033_3@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Icons/ic_closeGray.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Icons/ic_closeGray.imageset/btn_innerX.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Settings/Configurations/Config.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Settings/Info.plist
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/CustomEmptyView.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/DRBottomSheetViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/DRDimmedView.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/DRTextField.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/DRTimelineCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Utils/Enums/DRTextFieldType.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Utils/Enums/Header.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Base/NetworkService.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/SearchPlace/DTO/GetSearchPlaceRequest.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/SearchPlace/DTO/GetSearchPlaceResponse.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/SearchPlace/SearchPlaceService.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/SearchPlace/SearchPlaceTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Cells/AddSecondViewTableViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/ViewModels/AddCourseViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseFirst/AddCourseFirstViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseSecond/AddCourseSecondView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseSecond/AddCourseSecondViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddSheetViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/ViewModels/AddScheduleViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleBottomSheetViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleFirst/AddScheduleFirstViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleSecond/AddScheduleSecondView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleSecond/AddScheduleSecondViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Base/BaseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Commons/LocationFilter/Views/LocationFilterViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Commons/SearchPlace/Models/SearchPlaceModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Commons/SearchPlace/ViewModels/SearchPlaceViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Commons/SearchPlace/Views/Cells/SearchPlaceTableViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Commons/SearchPlace/Views/SearchPlaceView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Commons/SearchPlace/Views/SearchPlaceViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/DateDetailContentView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/EmptyTicketView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/EditProfileViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/ProfileViewController.swift
Labels: 🛠️ feature, 🐰 희슬

#304 [FEAT] 코스 상세, 일정 장세 장소 API 연결 및 반영 (#303)
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/DRTimelineCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/CourseDetail/CourseDetailTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/CourseDetail/DTO/GetCourseDetailResponse.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/DateSchedule/DTO/GetDateDetailResponse.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/DateSchedule/DateScheduleTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Models/CourseDetailModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/CourseDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateDetailViewModel.swift
Labels: 🛠️ feature

#302 [FEAT] 구글 애즈 적용(#297)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DATEROAD-iOS/DATEROAD-iOS/Application/AppDelegate.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Extensions/UIViewController+.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Protocols/GoogleAdsPresentable.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/PointDetail/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/PointDetail/btn_close.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/PointDetail/btn_close.imageset/btn_close.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/PointDetail/ic_rightarrow_purple.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/PointDetail/ic_rightarrow_purple.imageset/ic_rightarrow_purple.svg
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/PointDetail/img_advertise.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/PointDetail/img_advertise.imageset/img_advertise.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/PointDetail/img_advertise.imageset/img_advertise@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/PointDetail/img_advertise.imageset/img_advertise@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/PointDetail/img_course.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/PointDetail/img_course.imageset/img_course.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/PointDetail/img_course.imageset/img_course@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/PointDetail/img_course.imageset/img_course@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Service/GoogleAdsManager.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Settings/Configurations/Config.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Settings/Info.plist
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/CustomAlert/DRCustomAlertView.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Utils/Enums/GoogleAdsErrorType.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Utils/Enums/TextLabelType.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/PointDetail/PointDetailService.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/PointDetail/PointDetailTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Base/BaseNavBarViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/ViewModels/PointViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/Views/PointDetailView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/Views/PointDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/Views/PointShortageView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/Views/PointShortageViewController.swift
Labels: 🛠️ feature, 🐣 수민

#306 [FIX] 누락된 UI 속성 추가 (#305)
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/EmptyTicketView.swift
Labels: 🩹 fix, 🐼 신영

#312 [FIX] 3차 스프린트 1차 QA 적용 (#310)
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Protocols/DRButtonType.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/CustomAlert/DRCustomAlertView.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/CustomEmptyView.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/DRTimelineCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Utils/Enums/DRTextFieldType.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/AddCourse/AddCourseTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Cells/AddCourseImageCollectionViewCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseSecond/AddCourseSecondView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseThird/AddCourseThirdView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseThird/AddCourseThirdViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddSheetView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/ViewModels/AddScheduleViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleBottomSheetView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleFirst/InAddScheduleFirstView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleSecond/AddScheduleSecondViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleSecond/InAddScheduleSecondView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Base/BaseNavBarViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/DateDetailContentView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/Views/PointShortageViewController.swift
Labels: 🩹 fix, 🐼 신영

#308 [CHORE] 변경된 포인트내역 API 구조 반영 (#307)
  DATEROAD-iOS/DATEROAD-iOS/Network/PointDetail/DTO/GetPointDetailResponse.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/Models/PointModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/ViewModels/PointViewModel.swift
Labels: 🐣 수민, 🌀 chore

#313 [FIX] 3차 스프린트 1차 QA 적용 (#311)
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/ContentMaskView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/Cells/MyCourseListCollectionViewCell.swift
Labels: 🩹 fix, 🐣 수민

#314 [FIX] 3차 스프린트 1차 QA 적용 (#309)
  DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj
  DATEROAD-iOS/DATEROAD-iOS/Global/Extensions/UIFont+.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Protocols/DRButtonType.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Protocols/MainSectionLayout.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Protocols/Serviceable.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Main/floatingBtn.imageset/Contents.json
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Main/floatingBtn.imageset/btn_floatingadd.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Main/floatingBtn.imageset/btn_floatingadd@2x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Main/floatingBtn.imageset/btn_floatingadd@3x.png
  DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Fonts/AppleSDGothicNeoSB.ttf
  DATEROAD-iOS/DATEROAD-iOS/Global/Service/UserDefaultsManager.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Settings/Info.plist
  DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/DRErrorViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Global/Utils/Enums/TextButtonType.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/AddCourse/AddCourseTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/AddSchedule/AddScheduleTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Auth/AuthTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Course/CourseTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/CourseDetail/CourseDetailTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/CourseDetail/LikeCourseTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/CourseDetail/UsePointTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/DateSchedule/DateScheduleTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/Main/MainTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/MyCourse/MyCourseTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/PointDetail/PointDetailTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/User/UserService.swift
  DATEROAD-iOS/DATEROAD-iOS/Network/User/UserTargetType.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Banner/Views/BannerDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/ContentMaskView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/DeleteCourseSettingView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateDetailViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Login/ViewModels/LoginViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Login/Views/LoginView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Login/Views/LoginViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/ViewModels/MainViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/BannerCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/MainHeaderView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/NewDateCourseCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/UpcomingDateCell.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/ViewModels/MyCourseListViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/ViewedCourseView.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/ViewedCourseViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/ViewModels/MyPageViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/ViewModels/ProfileViewModel.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/ProfileViewController.swift
  DATEROAD-iOS/DATEROAD-iOS/Presentation/Splash/ViewModels/SplashViewModel.swift
Labels: 🩹 fix, 🐰 희슬
